### ISSUE TITLE
invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by lmilbaum** [rylarson/chef-java_properties#1]
The properties file is text/plain; charset=iso-8859-1

in chef recipe:

java_properties '/opt/IBM/JazzTeamServer/server/conf/dcc/teamserver.properties' do
  properties_file '/opt/IBM/JazzTeamServer/server/conf/dcc/teamserver.properties'
  property 'com.ibm.rational.datacollection.initialized', 'false'
  only_if { node['clm']['version'].to_s >=  '6.0.3' }
end

================================================================================
     Error executing action `merge` on resource 'java_properties[/opt/IBM/JazzTeamServer/server/conf/dcc/teamserver.properties]'
     ================================================================================
     
     ArgumentError
     -------------
     invalid byte sequence in UTF-8
     
     Cookbook Trace:
     ---------------
     /var/chef/cache/cookbooks/java_properties/files/default/vendor/gems/java-properties-0.0.2/lib/java-properties/parsing/normalizer.rb:38:in `gsub!'
     /var/chef/cache/cookbooks/java_properties/files/default/vendor/gems/java-properties-0.0.2/lib/java-properties/parsing/normalizer.rb:38:in `apply!'
     /var/chef/cache/cookbooks/java_properties/files/default/vendor/gems/java-properties-0.0.2/lib/java-properties/parsing/normalizer.rb:67:in `block in normalize!'
     /var/chef/cache/cookbooks/java_properties/files/default/vendor/gems/java-properties-0.0.2/lib/java-properties/parsing/normalizer.rb:66:in `each'
     /var/chef/cache/cookbooks/java_properties/files/default/vendor/gems/java-properties-0.0.2/lib/java-properties/parsing/normalizer.rb:66:in `normalize!'
     /var/chef/cache/cookbooks/java_properties/files/default/vendor/gems/java-properties-0.0.2/lib/java-properties/parsing/parser.rb:29:in `parse'
     /var/chef/cache/cookbooks/java_properties/files/default/vendor/gems/java-properties-0.0.2/lib/java-properties.rb:16:in `parse'
     /var/chef/cache/cookbooks/java_properties/files/default/vendor/gems/java-properties-0.0.2/lib/java-properties.rb:33:in `load'
     /var/chef/cache/cookbooks/java_properties/libraries/java_properties_resource.rb:50:in `properties_from_file'
     /var/chef/cache/cookbooks/java_properties/libraries/java_properties_resource.rb:79:in `action_merge'
     
     Resource Declaration:
     ---------------------
     # In /var/chef/cache/cookbooks/clm/recipes/patch.rb
     
      52: java_properties '/opt/IBM/JazzTeamServer/server/conf/dcc/teamserver.properties' do
      53:   properties_file '/opt/IBM/JazzTeamServer/server/conf/dcc/teamserver.properties'
      54:   property 'com.ibm.rational.datacollection.initialized', 'false'
      55:   only_if { node['clm']['version'].to_s >=  '6.0.3' }
      56: end
      57: 
     
     Compiled Resource:
     ------------------
     # Declared in /var/chef/cache/cookbooks/clm/recipes/patch.rb:52:in `from_file'
     
     java_properties("/opt/IBM/JazzTeamServer/server/conf/dcc/teamserver.properties") do
       provider Chef::Provider::JavaProperties
       action :merge
       retries 0
       retry_delay 2
       default_guard_interpreter :default
       properties_file "/opt/IBM/JazzTeamServer/server/conf/dcc/teamserver.properties"
       properties_from_attributes {:"com.ibm.rational.datacollection.initialized"=>"false"}
       declared_type :java_properties
       cookbook_name "clm"
       recipe_name "patch"
       only_if { #code block }
     end
     
     Platform:
     ---------
     x86_64-linux

**Comment by rylarson** [comment]
Hey there,

I have only ever seen this happen where there is some weird control character in the properties file. Can you post a sanitized properties file that exhibits the problem?

Thanks

Ryan

**Comment by lmilbaum** [comment]
Here is the content of the file:

#This configuration update was requested by "ADMIN".  The old contents of this file were copied to "/opt/IBM/JazzTeamServer/server/conf/dcc/teamserver-1484411254004bakup.properties".
#Sat Jan 14 16:27:34 UTC 2017
com.ibm.team.repository.server.jts.url=https\://ec2-52-31-187-252.eu-west-1.compute.amazonaws.com\:9443/jts
com.ibm.team.repository.db.jdbc.location=conf/dcc/derby/repositoryDB
com.ibm.team.repository.db.jdbc.password=[qoSGR4gvSUY\=]
com.ibm.team.jfs.index.root.directory=indices
com.ibm.team.repository.changeEvent.expirationDefault=1209600
com.ibm.rational.datacollection.initialized=true
com.ibm.team.repository.server.webapp.url=https\://ec2-52-31-187-252.eu-west-1.compute.amazonaws.com\:9443/dcc
com.ibm.team.repository.db.repoLockId=_NBwIYdp1EeaUuo3NzhdrTQ
com.ibm.team.datawarehouse.db.vendor=derby_net
com.ibm.team.repository.ws.allow.admin.access=false
com.ibm.team.repository.web.suppressedPages={"com.ibm.team.repository.web.admin"\: ["com.ibm.team.repository.provision"], "com.ibm.team.app.web.admin"\: ["com.ibm.team.process.ProjectAreaManagement", "com.ibm.team.process.ProcessTemplateManagement", "com.ibm.team.process.AccessGroupManagement"]}
com.ibm.team.repository.db.vendor=DERBY
com.ibm.team.datawarehouse.db.jdbc.password=[qoSGR4gvSUY\=]
com.ibm.rational.datacollection.ods.initial.schedule.type=daily
com.ibm.rational.datacollection.datamart.initial.schedule.interval=180
com.ibm.team.repository.db.type=JDBC
com.ibm.team.repository.web.helpuri=/clmhelp/index.jsp
com.ibm.team.repository.lastChange=Jazz Team Server,UPDATED,1484411095938
com.ibm.rational.datacollection.ods.initial.schedule.interval=0
com.ibm.team.datawarehouse.db.automatic.setup=true
com.ibm.rational.datacollection.license.initial.schedule.interval=60
com.ibm.team.fulltext.indexLocation=conf/dcc/indices/workitemindex
com.ibm.team.datawarehouse.db.jdbc.location=//localhost\:1527/conf/jts/derby/warehouseDB
com.ibm.team.repository.ws.allow.identity.assertion=false
com.ibm.team.datawarehouse.db.type=JDBC
com.ibm.rational.datacollection.license.initial.schedule.type=interval
com.ibm.team.repository.changeEvent.expirationByCategory=SystemLog\:259200
com.ibm.rational.datacollection.datamart.initial.schedule.type=daily
com.ibm.team.repository.cluster.isInCluster=false
com.ibm.team.datawarehouse.datawarehouse.jobs.enabled=true
com.ibm.team.repository.setup.registration.pendingOauthConsumer=
com.ibm.team.repository.setup.registration.pendingJtsFriend=

**Comment by lioramilbaum** [comment]
Ignore the previous comment. It wasn't the right version of the file.  How can I send you the right one?

**Comment by lmilbaum** [comment]
Ignore the previous comment. Wrong file version.  Attached the right one.

[teamserver.properties.txt](https://github.com/rylarson/chef-java_properties/files/706430/teamserver.properties.txt)

**Comment by lmilbaum** [comment]
BTW, it works perfectly for the first version.
